### ISSUE TITLE
Build fails in Debian Bullseye

### ISSUE THREAD

**Issue by AlexTMjugador** [philipl/nv-video-info#2]
For me, building this project on Debian Bullseye fails on the generated autoconf Makefile, complaining of `undefined reference to 'dlclose'`. Autoconf runs successfully. Am I doing something wrong?

GCC version:
```
$ gcc --version                                                                   
gcc (Debian 9.2.1-25) 9.2.1 20200123
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Kernel version:
```
$ uname -a
Linux pc 5.4.0-3-amd64 #1 SMP Debian 5.4.13-1 (2020-01-19) x86_64 GNU/Linux
```

autogen.sh output: https://pastebin.com/dRxcQsjs
Make output: https://pastebin.com/jDdyF4U0 (it doesn't go away by using `LDFLAGS=-Wl,--no-as-needed` as suggested on the Internet).

**Comment by philipl** [comment]
You need to have `libltdl-dev` installed. Its absence is why you see
```
./configure: line 3758: LT_LIB_DLLOAD: command not found
```
in your output. This is what ensures `dlclose` and friends are available.

**Comment by AlexTMjugador** [comment]
Thank you, @philipl. Installing the `libltdl-dev` package fixed it, and now everything compiles successfully.

As a suggestion, would it be possible to replace that error message with a more explicit, user-friendly one, like with other missing dependencies?
