### ISSUE TITLE
nvencinfo too long output

### ISSUE THREAD

**Issue by Saentist** [philipl/nv-video-info#5]
If do 
```shell
./nvencinfo > nve.txt
```
result is strange 65470 line's.
But only 82 of them are usefully.
[nve.txt](https://github.com/philipl/nv-video-info/files/7806098/nve.txt)

**Comment by philipl** [comment]
It's a bug in how the code handles hardware that only supports one encoding format (h.264)

**Comment by Saentist** [comment]
Is there a way to be limted this repeating?
